ARG version
FROM almalinux:${version:-9}
ENV course="DevOps with AWS" \
    trainer="sivakumar reddy" \
    duration="120HRS"
ARG Username=deepika
RUN echo "hi username: ${Username}"
CMD ["sleep", "100"]